services:
  08630628_0: &id001
    command: sleep 365d
    cpu_shares: 512
    cpuset: '0'
    image: ubuntu:14.04
    mem_limit: 1024m
    network_mode: none
    privileged: true
  47e364fd_0: *id001
  b53d792c_0: *id001
  router:
    command: sleep 365d
    image: ubuntu:14.04
    network_mode: none
    privileged: true
version: '2'
