services:
  08630628_0: &id001
    command: sleep 365d
    cpu_shares: 512
    cpuset: '0'
    image: Ubuntu 14.04
    mem_limit: 256m
    network_mode: none
    privileged: true
  08630628_1: *id001
  08630628_2: *id001
  08630628_3: *id001
  47e364fd_0: *id001
  cf1f51ff_1: *id001
  router:
    command: sleep 365d
    image: ubuntu:14.04
    network_mode: none
    privileged: true
version: '2'
