services:
  55d73584_0:
    cpu_shares: 512
    cpuset: '0'
    image: irc-bot-docker:latest
    mem_limit: 512m
    network_mode: none
    privileged: true
  ad2fe61a_0:
    cpu_shares: 512
    cpuset: '0'
    image: irc-bot-docker:latest
    mem_limit: 512m
    network_mode: none
    privileged: true
  d6ed5c14_0:
    cpu_shares: 512
    cpuset: 0,1
    image: irc-server-docker:latest
    mem_limit: 256m
    network_mode: none
    privileged: true
  router:
    command: sleep 365d
    image: router-docker:latest
    network_mode: none
    privileged: true
version: '2'
