services:
  26b952c7_1:
    cpu_shares: 512
    cpuset: '0'
    expose:
    - '80'
    image: irc-bot-docker:noclient
    mem_limit: 256m
    network_mode: none
    privileged: true
  5493000e_0:
    cpu_shares: 512
    cpuset: 0,1
    expose:
    - '80'
    image: irc-bot-docker:latest
    mem_limit: 256m
    network_mode: none
    privileged: true
  router_26b952c7:
    command: sleep 365d
    image: router-docker:latest
    network_mode: none
    privileged: true
  router_535ac689:
    command: sleep 365d
    image: router-docker:latest
    network_mode: none
    privileged: true
  router_5493000e:
    command: sleep 365d
    image: router-docker:latest
    network_mode: none
    privileged: true
  router_62d1df84:
    command: sleep 365d
    image: router-docker:latest
    network_mode: none
    privileged: true
  router_882c7c44:
    command: sleep 365d
    image: router-docker:latest
    network_mode: none
    privileged: true
  router_b0b2a443:
    command: sleep 365d
    image: router-docker:latest
    network_mode: none
    privileged: true
version: '2'
