#this is irc-bot 1.4.1,revceive ip of irc-server from args,change the images,add net-tools
#2016.8.7  autorun Botlient
#2016.8.8  test the server befor running botclient

FROM ircbot:1.3

MAINTAINER nyd "niyuandong@wis-eye.com"

ADD start.sh /start.sh

RUN chmod +x start.sh

CMD ["/bin/bash","/start.sh"]


